### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/a/pycharmcode/Animal-sound-recognition-main/indices/unbalanced_train_segments_clean.csv'

### ISSUE THREAD

**Issue by switchnight** [jovan-stojanovic/Animal-sound-recognition#3]
/home/a/anaconda3/envs/as1/bin/python /home/a/pycharmcode/Animal-sound-recognition-main/dataset/download_and_pack.py 
/home/a/anaconda3/envs/as1/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/home/a/pycharmcode/Animal-sound-recognition-main/dataset/download_and_pack.py", line 208, in <module>
    split_unbalanced_csv_to_partial_csvs(args)
  File "/home/a/pycharmcode/Animal-sound-recognition-main/dataset/download_and_pack.py", line 26, in split_unbalanced_csv_to_partial_csvs
    with open(unbalanced_csv_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/a/pycharmcode/Animal-sound-recognition-main/indices/unbalanced_train_segments_clean.csv'

进程已结束,退出代码1

**Comment by switchnight** [comment]
no this file in your item
